version: '3'
services:
  # app:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  db:
    image: mysql:9.1
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
