// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
)

type Item struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Price       string         `json:"price"`
	Description sql.NullString `json:"description"`
	Stock       int32          `json:"stock"`
}

type User struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UserItem struct {
	UserID       int32        `json:"user_id"`
	ItemID       int32        `json:"item_id"`
	Quantity     int32        `json:"quantity"`
	PurchaseDate sql.NullTime `json:"purchase_date"`
}
